name: C/C++ CI (x86/vac/hw-operations-in-vac-v3)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: 
      - self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: ./scripts/download-prebuilt
      run: ./scripts/download-prebuilt
    - name: make x64
      run: make x64 -j`nproc`
    - name: boot-test.exp
      run: .github/workflows/boot-test.exp
    - name: make arm64
      run: make arm64 -j`nproc`
